groq:
  api_key: $GROQ_API_KEY
  chat_model: "llama-3.1-70b-versatile"
  whisper_model: "whisper-large-v3"
  temperature: 0
  max_tokens: 512

qdrant:
  url: $QDRANT_URL
  api_key: $QDRANT_API_KEY

prompts:
  chat:
    filepath: "./src/prompts/chat/system.txt"

  functions:
    filepath: "./src/prompts/functions/signatures.json"

google:
  api_key: $GOOGLE_API_KEY
  embedding_model: "models/text-multilingual-embedding-002"

